---
- name: set user's settings for programs and packages
  block:
    - name: create new directories to store user's settings on the current machine
      file:
        path: "{{ item.dest | dirname }}" # get the absolute path to store this file on the current machine
        state: directory
        recurse: false
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0755
      with_items: "{{ dotfiles_list }}"

    - name: set user's settings for the required programs and packages on the current operating system
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644
      with_items: "{{ dotfiles_list }}"
  when: ansible_distribution | lower == "fedora"
  tags:
    - dotfiles
    - dotfiles-workstation
