#!/usr/bin/env sh

# Copyright 2020 (c) Vladislav Punko <iam.vlad.punko@gmail.com>

set -o errexit
set -o nounset

if [ -f /etc/redhat-release ] && grep --ignore-case --quiet fedora /etc/redhat-release; then
  # Ask for the administrator's password in advance.
  sudo --validate

  # Keep-alive: update the existing user's password timestamp until the completion of this script on the current machine.
  while true; do sudo --non-interactive true; sleep 60; kill -s 0 "$$" || exit; done 2> /dev/null &

  # Check the repositories for newer packages and updates them.
  sudo dnf update --refresh --assumeyes

  # Clean all package cache.
  sudo dnf clean all

  # Update the main virus database on the current machine.
  sudo freshclam --show-progress
fi

if [ "$(uname)" = 'Darwin' ]; then
  brew update

  # Upgrade all homebrew-installed packages to their latest versions.
  brew upgrade
  brew upgrade --cask --greedy

  # Remove all content from the homebrew cache directory.
  rm -f -r -- "$(brew --cache)"
fi

# Update all programs and packages of the main scientific computation system.
"${HOME}/.miniconda/bin/conda" update --update-all --yes
