#!/usr/bin/env sh

# Copyright 2020 (c) Vladislav Punko <iam.vlad.punko@gmail.com>

set -o errexit
set -o nounset

brew update

# Upgrade all homebrew-installed packages to their latest versions.
brew upgrade
brew upgrade --cask --greedy

# Remove all content from the homebrew cache directory.
rm -f -r -- "$(brew --cache)"

# Update the main virus database on the current machine.
freshclam --show-progress

# Update all programs and packages of the main scientific computation system.
"${HOME}/.miniconda/bin/conda" update --update-all --yes
