---
version: "3"

services:
  devbox:
    # Step -- 1.
    container_name: devbox

    # Step -- 2.
    command: tail -F /dev/null  # keep container running
    stdin_open: true
    tty: true
    restart: unless-stopped

    # Step -- 3.
    image: ubuntu:latest

    # Step -- 4.
    volumes:
      - ~/Projects:/root/Projects:Z
